FROM golang:1.22.5

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY ./config/go.* ./
RUN go mod download

COPY ./config/.air.toml ./
COPY srcs srcs

EXPOSE 5000

CMD ["air", "-c", ".air.toml"]
