# Config file for Air
[build]
	# Command to build the app
	cmd = "go build -o main srcs/main.go"
	bin = "main"
	dir = "srcs"
	include_ext = ["go"]
	exclude_dir = ["vendor"]
	run_after_build = "chmod +x main"
[log]
	level = "debug"
